CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR(14),
	@ID BIGINT
AS
BEGIN
	IF @ID = -1
		BEGIN
			SELECT 1 FROM CLIENTES WHERE CPF = @CPF 
		END
	ELSE
		BEGIN
			SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND CLIENTES.ID != @ID
		END
END